apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: planpal
  namespace: argocd
spec:
  description: PlanPal Helm chart
  sourceRepos:
    - https://gitlab-g3-nar.sandbox.devopsinstitute.id/administrator/helm_planpal_ch3.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: planpal
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
