apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: planpal
  namespace: argocd
spec:
  project: planpal
  source:
    repoURL: https://gitlab-g3-nar.sandbox.devopsinstitute.id/administrator/helm_planpal_ch3.git
    targetRevision: main
    path: .
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: planpal
  syncPolicy: {}
