
image:
  tag: v1.0.0

ingress:
  enabled: true
  className: alb
  host: ch4-g3-nar.sandbox.devopsinstitute.id
  certificateArn: arn:aws:acm:ap-southeast-3:134604498185:certificate/d2af9d54-2b41-4ff0-97c0-a59d8674802e
  healthcheckPath: /api/v1/health
  groupName: global-alb
  groupOrder: 10

externalSecrets:
  enabled: true
  region: ap-southeast-3
  awsSecretName: ch4-g3-secret-nar
  refreshInterval: 1h

workloads:
  postgres:
    enabled: false

  redis:
    enabled: true
  nats:
    enabled: true

  server:
    replicas: 2
    hpa:
      enabled: true
      minReplicas: 2
      maxReplicas: 5
    rollout:
      enabled: true
      strategy: blueGreen
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 30

  frontend:
    replicas: 2
    hpa:
      enabled: true
      minReplicas: 2
      maxReplicas: 5
