apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: planpal-frontend-secret
  namespace: planpal
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: planpal-frontend-secret
    creationPolicy: Owner
  data:
    - secretKey: SECRET_FIREBASE_API_KEY
      remoteRef: { key: ch4-g3-secret-nar, property: SECRET_FIREBASE_API_KEY }
    - secretKey: SECRET_FIREBASE_AUTH_DOMAIN
      remoteRef: { key: ch4-g3-secret-nar, property: SECRET_FIREBASE_AUTH_DOMAIN }
    - secretKey: SECRET_FIREBASE_PROJECT_ID
      remoteRef: { key: ch4-g3-secret-nar, property: SECRET_FIREBASE_PROJECT_ID }
    - secretKey: SECRET_FIREBASE_STORAGE_BUCKET
      remoteRef: { key: ch4-g3-secret-nar, property: SECRET_FIREBASE_STORAGE_BUCKET }
    - secretKey: SECRET_FIREBASE_MESSAGING_SENDER_ID
      remoteRef: { key: ch4-g3-secret-nar, property: SECRET_FIREBASE_MESSAGING_SENDER_ID }
    - secretKey: SECRET_FIREBASE_APP_ID
      remoteRef: { key: ch4-g3-secret-nar, property: SECRET_FIREBASE_APP_ID }
    - secretKey: SECRET_FIREBASE_MEASUREMENT_ID
      remoteRef: { key: ch4-g3-secret-nar, property: SECRET_FIREBASE_MEASUREMENT_ID }
    - secretKey: SECRET_FIREBASE_VAPID_KEY
      remoteRef: { key: ch4-g3-secret-nar, property: SECRET_FIREBASE_VAPID_KEY }
