apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: planpal-seed-admin-secret
  namespace: planpal
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: planpal-seed-admin-secret
    creationPolicy: Owner
  data:
    - secretKey: SEED_ADMIN_EMAIL
      remoteRef: { key: ch4-g3-secret-nar, property: SEED_ADMIN_EMAIL }
    - secretKey: SEED_ADMIN_PASSWORD
      remoteRef: { key: ch4-g3-secret-nar, property: SEED_ADMIN_PASSWORD }
    - secretKey: SEED_ADMIN_NAME
      remoteRef: { key: ch4-g3-secret-nar, property: SEED_ADMIN_NAME }
