apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: planpal-secret
  namespace: planpal
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: planpal-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef: { key: ch4-g3-secret-nar, property: POSTGRES_PASSWORD }
    - secretKey: SECRET_DATABASE_URL
      remoteRef: { key: ch4-g3-secret-nar, property: SECRET_DATABASE_URL }
    - secretKey: SECRET_JWT_SECRET
      remoteRef: { key: ch4-g3-secret-nar, property: SECRET_JWT_SECRET }
    - secretKey: SECRET_AI_API_KEY
      remoteRef: { key: ch4-g3-secret-nar, property: SECRET_AI_API_KEY }
    - secretKey: SECRET_GOOGLE_CLIENT_SECRET
      remoteRef: { key: ch4-g3-secret-nar, property: SECRET_GOOGLE_CLIENT_SECRET }
    - secretKey: SECRET_SMTP_USERNAME
      remoteRef: { key: ch4-g3-secret-nar, property: SECRET_SMTP_USERNAME }
    - secretKey: SECRET_SMTP_PASSWORD
      remoteRef: { key: ch4-g3-secret-nar, property: SECRET_SMTP_PASSWORD }
    - secretKey: SECRET_FCM_SERVICE_ACCOUNT_JSON
      remoteRef: { key: ch4-g3-secret-nar, property: SECRET_FCM_SERVICE_ACCOUNT_JSON }
    - secretKey: SECRET_SLACK_SIGNING_SECRET
      remoteRef: { key: ch4-g3-secret-nar, property: SECRET_SLACK_SIGNING_SECRET }
    - secretKey: SECRET_SLACK_BOT_TOKEN
      remoteRef: { key: ch4-g3-secret-nar, property: SECRET_SLACK_BOT_TOKEN }
