apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: planpal-tls-secret
  namespace: planpal
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: planpal-tls-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef: { key: ch4-g3-secret-nar, property: TLS_CRT }
    - secretKey: tls.key
      remoteRef: { key: ch4-g3-secret-nar, property: TLS_KEY }
